using Beneficios.Domain.Enums;

namespace Beneficios.Application.DTOs;

public record FuncionarioBeneficioDto(
    Guid Id,
    string CodigoBeneficio,
    bool Ativo,
    DateOnly? DataInicio,
    DateOnly? DataFim,
    bool OptIn);

public record FuncionarioDto(
    Guid Id,
    string Nome,
    string Cpf,
    string? Matricula,
    DateOnly DataAdmissao,
    DateOnly? DataDesligamento,
    string Cargo,
    decimal SalarioBase,
    TipoContrato TipoContrato,
    string? CentroCusto,
    string? ResCep,
    string? ResLogradouro,
    string? ResNumero,
    string? ResComplemento,
    string? ResBairro,
    string? ResCidade,
    string? ResUf,
    string? TrabNomeLocal,
    string? TrabCep,
    string? TrabLogradouro,
    string? TrabNumero,
    string? TrabComplemento,
    string? TrabBairro,
    string? TrabCidade,
    string? TrabUf,
    SituacaoFuncionario Situacao,
    string? MotivoAfastamento,
    JornadaTrabalho Jornada,
    string? JornadaDetalhe,
    DateTime DataInclusao,
    DateTime? DataAlteracao,
    IReadOnlyList<FuncionarioBeneficioDto> Beneficios);

public record FuncionarioBeneficioSalvarDto(
    string CodigoBeneficio,
    bool Ativo,
    DateOnly? DataInicio,
    DateOnly? DataFim,
    bool OptIn);

public record FuncionarioSalvarDto(
    string Nome,
    string Cpf,
    string? Matricula,
    DateOnly DataAdmissao,
    DateOnly? DataDesligamento,
    string Cargo,
    decimal SalarioBase,
    TipoContrato TipoContrato,
    string? CentroCusto,
    string? ResCep,
    string? ResLogradouro,
    string? ResNumero,
    string? ResComplemento,
    string? ResBairro,
    string? ResCidade,
    string? ResUf,
    string? TrabNomeLocal,
    string? TrabCep,
    string? TrabLogradouro,
    string? TrabNumero,
    string? TrabComplemento,
    string? TrabBairro,
    string? TrabCidade,
    string? TrabUf,
    SituacaoFuncionario Situacao,
    string? MotivoAfastamento,
    JornadaTrabalho Jornada,
    string? JornadaDetalhe,
    IReadOnlyList<FuncionarioBeneficioSalvarDto>? Beneficios);

public record FuncionarioAtualizarDto(
    string Nome,
    string Cpf,
    string? Matricula,
    DateOnly DataAdmissao,
    DateOnly? DataDesligamento,
    string Cargo,
    decimal SalarioBase,
    TipoContrato TipoContrato,
    string? CentroCusto,
    string? ResCep,
    string? ResLogradouro,
    string? ResNumero,
    string? ResComplemento,
    string? ResBairro,
    string? ResCidade,
    string? ResUf,
    string? TrabNomeLocal,
    string? TrabCep,
    string? TrabLogradouro,
    string? TrabNumero,
    string? TrabComplemento,
    string? TrabBairro,
    string? TrabCidade,
    string? TrabUf,
    SituacaoFuncionario Situacao,
    string? MotivoAfastamento,
    JornadaTrabalho Jornada,
    string? JornadaDetalhe,
    IReadOnlyList<FuncionarioBeneficioSalvarDto>? Beneficios);

public record FuncionarioFiltroDto(
    string? Nome,
    string? Cpf,
    string? Matricula,
    SituacaoFuncionario? Situacao);
